import {firebaseConfig} from './firebase-config.js';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,signInAnonymously} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,collection,doc,addDoc,setDoc,updateDoc,deleteDoc,onSnapshot,serverTimestamp,query,orderBy,getDoc,getDocs,writeBatch} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let db,view='dashboard',tasks=[],categories=[],flows=[],checks=[],people=[],settings={title:'婚禮工作中心',weddingDate:'',initialized:false};
let currentUser=localStorage.getItem('wccUser')||'';
const defaults={categories:[['文定準備','💍'],['迎娶準備','🚗'],['婚宴準備','🥂'],['攝影錄影','📸']],tasks:[['十二禮準備完成','物品','文定準備'],['奉茶名單確認','工作','文定準備'],['禮車與集合時間確認','工作','迎娶準備'],['主持流程確認','工作','婚宴準備']],flows:[['08:00','集合','📍'],['09:00','文定','💍'],['11:00','迎娶','🚗'],['18:00','婚宴','🥂']]};
const category=id=>categories.find(x=>x.id===id), linkedTask=id=>tasks.find(x=>x.id===id);

function setView(v){view=v;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===v));render()}
$('#tabs').onclick=e=>{const b=e.target.closest('[data-view]');if(b)setView(b.dataset.view)};
function renderHeader(){$('#appTitle').textContent=settings.title||'婚禮工作中心';$('#currentUser').textContent=currentUser?`目前使用者：${currentUser}`:'尚未設定使用者'}
const pct=list=>list.length?Math.round(list.filter(x=>x.done).length/list.length*100):0;
function daysLeft(){if(!settings.weddingDate)return '未設定';const now=new Date();now.setHours(0,0,0,0);return Math.ceil((new Date(settings.weddingDate+'T00:00:00')-now)/86400000)}
function renderDashboard(){const d=daysLeft();$('#dashboard').innerHTML=`<div class="grid"><div class="stat"><div class="meta">距離婚禮</div><div class="big">${d}${typeof d==='number'?' 天':''}</div></div><div class="stat"><div class="meta">前置準備完成率</div><div class="big">${pct(tasks)}%</div><div class="progress"><span style="width:${pct(tasks)}%"></span></div></div><div class="stat"><div class="meta">流程確認完成率</div><div class="big">${pct(checks)}%</div><div class="progress"><span style="width:${pct(checks)}%"></span></div></div><div class="stat"><div class="meta">我的未完成工作</div><div class="big">${tasks.filter(x=>x.owner===currentUser&&!x.done).length}</div></div></div><div class="quick"><button data-jump="prepare">📋 前置準備</button><button data-jump="timeline">🎬 婚禮流程</button><button data-jump="mine">👤 我的任務</button><button data-jump="people">👥 人員</button></div>`}
function taskRow(t){const c=category(t.categoryId);return `<div class="row ${t.done?'done':''}"><input class="check" type="checkbox" data-action="toggle-task" data-id="${t.id}" ${t.done?'checked':''}><div class="main"><div class="name">${esc(t.title)}</div><div class="meta">${c?`${esc(c.icon)} ${esc(c.name)}・`:''}${esc(t.type||'工作')}<br>DRI：${esc(t.owner||'未指定')}${t.notes?`<br>${esc(t.notes)}`:''}</div></div><div class="actions"><button class="small" data-action="edit-task" data-id="${t.id}">修改</button><button class="small danger" data-action="delete-task" data-id="${t.id}">刪除</button></div></div>`}
function renderPrepare(){$('#prepare').innerHTML=`<div class="toolbar"><button class="primary" data-action="new-category">新增分類</button><button class="primary" data-action="new-task">新增工作</button></div>${categories.map(c=>{const list=tasks.filter(t=>t.categoryId===c.id);return `<div class="card"><div class="card-head"><div><div class="card-title">${esc(c.icon||'📂')} ${esc(c.name)}</div><div class="meta">${list.filter(x=>x.done).length}/${list.length}</div></div><div class="actions"><button class="small" data-action="move-category-up" data-id="${c.id}">上移</button><button class="small" data-action="move-category-down" data-id="${c.id}">下移</button><button class="small" data-action="edit-category" data-id="${c.id}">修改</button></div></div>${list.map(taskRow).join('')||'<div class="empty">此分類沒有工作</div>'}</div>`}).join('')}`}
function flowCard(f){const list=checks.filter(x=>x.flowId===f.id);return `<div class="flow-card card"><div class="card-head"><div><div class="card-title">${esc(f.time||'--:--')}　${esc(f.icon||'📍')} ${esc(f.name)}</div><div class="meta">負責人：${esc(f.owner||'未指定')}・確認 ${list.filter(x=>x.done).length}/${list.length}</div>${f.notes?`<div class="meta">${esc(f.notes)}</div>`:''}</div><div class="actions"><button class="small" data-action="move-flow-up" data-id="${f.id}">上移</button><button class="small" data-action="move-flow-down" data-id="${f.id}">下移</button><button class="small" data-action="add-check" data-id="${f.id}">加確認項</button><button class="small" data-action="edit-flow" data-id="${f.id}">修改</button><button class="small danger" data-action="delete-flow" data-id="${f.id}">刪除</button></div></div>${list.map(ch=>{const t=linkedTask(ch.taskId);return `<div class="row ${ch.done?'done':''}"><input class="check" type="checkbox" data-action="toggle-check" data-id="${ch.id}" ${ch.done?'checked':''}><div class="main"><div class="name">${esc(ch.title)}</div><div class="meta">負責：${esc(ch.owner||'未指定')}${t?`<br>前置狀態：${t.done?'✅ 已準備':'⚠️ 尚未準備'}`:''}</div></div><div class="actions"><button class="small" data-action="edit-check" data-id="${ch.id}">修改</button><button class="small danger" data-action="delete-check" data-id="${ch.id}">刪除</button></div></div>`}).join('')||'<div class="empty">尚未建立確認項目</div>'}</div>`}
function renderTimeline(){$('#timeline').innerHTML=`<div class="toolbar"><button class="primary" data-action="new-flow">新增流程</button></div><div class="timeline-line">${flows.map(flowCard).join('')||'<div class="empty">尚未建立流程</div>'}</div>`}
function renderMine(){const myWork=tasks.filter(x=>x.owner===currentUser),myFlow=checks.filter(x=>x.owner===currentUser);$('#mine').innerHTML=`<div class="card"><div class="card-head"><div class="card-title">📝 我的工作</div></div>${myWork.map(taskRow).join('')||'<div class="empty">目前沒有分配的工作</div>'}</div><div class="card"><div class="card-head"><div class="card-title">🎬 我的流程</div></div>${myFlow.map(ch=>`<div class="row ${ch.done?'done':''}"><input class="check" type="checkbox" data-action="toggle-check" data-id="${ch.id}" ${ch.done?'checked':''}><div class="main"><div class="name">${esc(ch.title)}</div><div class="meta">${esc(flows.find(f=>f.id===ch.flowId)?.name||'未指定流程')}</div></div></div>`).join('')||'<div class="empty">目前沒有流程工作</div>'}</div>`}
function renderPeople(){$('#people').innerHTML=`<div class="toolbar"><button class="primary" data-action="new-person">新增人員</button></div>${people.map(p=>`<div class="person-card"><div><strong>${esc(p.name)}</strong><div class="meta">${esc(p.role||'未設定角色')}・工作 ${tasks.filter(x=>x.owner===p.name).length}・流程 ${checks.filter(x=>x.owner===p.name).length}</div></div><div class="actions"><button class="small" data-action="show-person" data-id="${p.id}">查看</button><button class="small" data-action="edit-person" data-id="${p.id}">修改</button><button class="small danger" data-action="delete-person" data-id="${p.id}">刪除</button></div></div>`).join('')||'<div class="empty">尚未建立人員</div>'}`}
function renderSettings(){$('#settings').innerHTML=`<div class="card"><div class="card-head"><div class="card-title">設定</div></div><div style="padding:16px"><label>網站名稱<input id="settingTitle" value="${esc(settings.title||'')}"></label><label>婚禮日期<input id="settingDate" type="date" value="${esc(settings.weddingDate||'')}"></label><div class="actions"><button class="primary" data-action="save-settings">儲存設定</button><button id="changeUser">更改目前使用者</button><button data-action="export-csv">匯出 CSV</button><button data-action="print">列印</button></div></div></div>`;$('#changeUser').onclick=openUser}
function render(){renderHeader();({dashboard:renderDashboard,prepare:renderPrepare,timeline:renderTimeline,mine:renderMine,people:renderPeople,settings:renderSettings}[view])()}
document.body.addEventListener('click',e=>{const j=e.target.closest('[data-jump]');if(j)setView(j.dataset.jump)});
function close(id){const d=document.getElementById(id);if(d?.open)d.close()}
document.body.addEventListener('click',e=>{const c=e.target.closest('[data-close]');if(c){close(c.dataset.close);return}if(e.target.tagName==='DIALOG')e.target.close()});
function openUser(){$('#userName').value=currentUser;$('#userDialog').showModal()}
$('#userForm').onsubmit=e=>{e.preventDefault();currentUser=$('#userName').value.trim();localStorage.setItem('wccUser',currentUser);close('userDialog');render()};
function fillCategorySelect(){$('#taskCategory').innerHTML=categories.map(c=>`<option value="${c.id}">${esc(c.icon)} ${esc(c.name)}</option>`).join('')}
function openTask(t=null){$('#taskDialogTitle').textContent=t?'修改前置工作':'新增前置工作';$('#taskId').value=t?.id||'';fillCategorySelect();$('#taskCategory').value=t?.categoryId||categories[0]?.id||'';$('#taskTitle').value=t?.title||'';$('#taskType').value=t?.type||'工作';$('#taskOwner').value=t?.owner||'';$('#taskNotes').value=t?.notes||'';$('#taskDialog').showModal()}
$('#taskForm').onsubmit=async e=>{e.preventDefault();const id=$('#taskId').value,p={title:$('#taskTitle').value.trim(),categoryId:$('#taskCategory').value,type:$('#taskType').value,owner:$('#taskOwner').value.trim(),notes:$('#taskNotes').value.trim(),updatedAt:serverTimestamp()};id?await updateDoc(doc(db,'wccTasks',id),p):await addDoc(collection(db,'wccTasks'),{...p,done:false,sort:tasks.length,createdAt:serverTimestamp()});close('taskDialog')};
function openFlow(f=null){$('#flowDialogTitle').textContent=f?'修改流程':'新增流程';$('#flowId').value=f?.id||'';$('#flowTime').value=f?.time||'';$('#flowName').value=f?.name||'';$('#flowIcon').value=f?.icon||'📍';$('#flowOwner').value=f?.owner||'';$('#flowNotes').value=f?.notes||'';$('#flowDialog').showModal()}
$('#flowForm').onsubmit=async e=>{e.preventDefault();const id=$('#flowId').value,p={time:$('#flowTime').value,name:$('#flowName').value.trim(),icon:$('#flowIcon').value.trim()||'📍',owner:$('#flowOwner').value.trim(),notes:$('#flowNotes').value.trim(),updatedAt:serverTimestamp()};id?await updateDoc(doc(db,'wccFlows',id),p):await addDoc(collection(db,'wccFlows'),{...p,sort:flows.length,createdAt:serverTimestamp()});close('flowDialog')};
function openCheck(ch=null,flowId=''){$('#checkDialogTitle').textContent=ch?'修改流程確認項目':'新增流程確認項目';$('#checkId').value=ch?.id||'';$('#checkFlowId').value=ch?.flowId||flowId;$('#checkTitle').value=ch?.title||'';$('#checkOwner').value=ch?.owner||'';$('#checkTaskLink').innerHTML='<option value="">不連結</option>'+tasks.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('');$('#checkTaskLink').value=ch?.taskId||'';$('#checkDialog').showModal()}
$('#checkForm').onsubmit=async e=>{e.preventDefault();const id=$('#checkId').value,p={flowId:$('#checkFlowId').value,title:$('#checkTitle').value.trim(),owner:$('#checkOwner').value.trim(),taskId:$('#checkTaskLink').value,updatedAt:serverTimestamp()};id?await updateDoc(doc(db,'wccFlowChecks',id),p):await addDoc(collection(db,'wccFlowChecks'),{...p,done:false,sort:checks.filter(x=>x.flowId===p.flowId).length,createdAt:serverTimestamp()});close('checkDialog')};
function openPerson(p=null){$('#personDialogTitle').textContent=p?'修改人員':'新增人員';$('#personId').value=p?.id||'';$('#personName').value=p?.name||'';$('#personRole').value=p?.role||'';$('#personDialog').showModal()}
$('#personForm').onsubmit=async e=>{e.preventDefault();const id=$('#personId').value,p={name:$('#personName').value.trim(),role:$('#personRole').value.trim(),updatedAt:serverTimestamp()};id?await updateDoc(doc(db,'wccPeople',id),p):await addDoc(collection(db,'wccPeople'),{...p,createdAt:serverTimestamp()});close('personDialog')};
function openCategory(c=null){$('#categoryDialogTitle').textContent=c?'修改分類':'新增分類';$('#categoryId').value=c?.id||'';$('#categoryName').value=c?.name||'';$('#categoryIcon').value=c?.icon||'📂';$('#categoryDialog').showModal()}
$('#categoryForm').onsubmit=async e=>{e.preventDefault();const id=$('#categoryId').value,p={name:$('#categoryName').value.trim(),icon:$('#categoryIcon').value.trim()||'📂',updatedAt:serverTimestamp()};id?await updateDoc(doc(db,'wccCategories',id),p):await addDoc(collection(db,'wccCategories'),{...p,sort:categories.length,createdAt:serverTimestamp()});close('categoryDialog')};
async function swapOrder(list,coll,id,dir){const i=list.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=list.length)return;const a=list[i],b=list[j],batch=writeBatch(db);batch.update(doc(db,coll,a.id),{sort:b.sort??j});batch.update(doc(db,coll,b.id),{sort:a.sort??i});await batch.commit()}
function csvExport(){const rows=[['類型','名稱','分類/流程','負責人','完成']];tasks.forEach(t=>rows.push(['前置',t.title,category(t.categoryId)?.name||'',t.owner||'',t.done?'是':'否']));checks.forEach(c=>rows.push(['流程',c.title,flows.find(f=>f.id===c.flowId)?.name||'',c.owner||'',c.done?'是':'否']));const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='wedding-control-center.csv';a.click();URL.revokeObjectURL(a.href)}
document.body.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
if(a==='new-task')openTask();if(a==='edit-task')openTask(tasks.find(x=>x.id===id));if(a==='delete-task'&&confirm('刪除此工作？'))await deleteDoc(doc(db,'wccTasks',id));if(a==='toggle-task')await updateDoc(doc(db,'wccTasks',id),{done:b.checked,updatedAt:serverTimestamp(),updatedBy:currentUser});
if(a==='new-flow')openFlow();if(a==='edit-flow')openFlow(flows.find(x=>x.id===id));if(a==='delete-flow'&&confirm('刪除此流程與確認項目？')){const batch=writeBatch(db);checks.filter(x=>x.flowId===id).forEach(x=>batch.delete(doc(db,'wccFlowChecks',x.id)));batch.delete(doc(db,'wccFlows',id));await batch.commit()}
if(a==='add-check')openCheck(null,id);if(a==='edit-check')openCheck(checks.find(x=>x.id===id));if(a==='delete-check'&&confirm('刪除此確認項目？'))await deleteDoc(doc(db,'wccFlowChecks',id));if(a==='toggle-check')await updateDoc(doc(db,'wccFlowChecks',id),{done:b.checked,updatedAt:serverTimestamp(),checkedBy:currentUser});
if(a==='new-person')openPerson();if(a==='edit-person')openPerson(people.find(x=>x.id===id));if(a==='delete-person'&&confirm('刪除此人員？'))await deleteDoc(doc(db,'wccPeople',id));if(a==='show-person'){const p=people.find(x=>x.id===id);if(p){currentUser=p.name;localStorage.setItem('wccUser',p.name);setView('mine')}}
if(a==='new-category')openCategory();if(a==='edit-category')openCategory(categories.find(x=>x.id===id));if(a==='move-category-up')await swapOrder(categories,'wccCategories',id,-1);if(a==='move-category-down')await swapOrder(categories,'wccCategories',id,1);if(a==='move-flow-up')await swapOrder(flows,'wccFlows',id,-1);if(a==='move-flow-down')await swapOrder(flows,'wccFlows',id,1);
if(a==='save-settings')await setDoc(doc(db,'wccSettings','main'),{title:$('#settingTitle').value.trim(),weddingDate:$('#settingDate').value,initialized:true},{merge:true});if(a==='export-csv')csvExport();if(a==='print')window.print();});
$('#fab').onclick=()=>view==='prepare'?openTask():view==='timeline'?openFlow():view==='people'?openPerson():openTask();
async function bootstrap(){const ref=doc(db,'wccSettings','main'),snap=await getDoc(ref);if(snap.exists()&&snap.data().initialized)return;const cs=await getDocs(collection(db,'wccCategories'));if(!cs.empty){await setDoc(ref,{initialized:true,title:'婚禮工作中心'},{merge:true});return}const batch=writeBatch(db),catRefs={};defaults.categories.forEach(([name,icon],i)=>{const r=doc(collection(db,'wccCategories'));catRefs[name]=r;batch.set(r,{name,icon,sort:i,createdAt:serverTimestamp()})});defaults.tasks.forEach(([title,type,c],i)=>{const r=doc(collection(db,'wccTasks'));batch.set(r,{title,type,categoryId:catRefs[c].id,owner:'',notes:'',done:false,sort:i,createdAt:serverTimestamp()})});defaults.flows.forEach(([time,name,icon],i)=>{const r=doc(collection(db,'wccFlows'));batch.set(r,{time,name,icon,owner:'',notes:'',sort:i,createdAt:serverTimestamp()})});batch.set(ref,{initialized:true,title:'婚禮工作中心',weddingDate:''});await batch.commit()}
async function start(){if(!currentUser)openUser();const app=initializeApp(firebaseConfig),auth=getAuth(app);db=getFirestore(app);await signInAnonymously(auth);$('#syncState').className='sync ok';$('#syncState').textContent='已連線・多人即時同步';await bootstrap();onSnapshot(query(collection(db,'wccTasks'),orderBy('sort','asc')),s=>{tasks=s.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(query(collection(db,'wccCategories'),orderBy('sort','asc')),s=>{categories=s.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(query(collection(db,'wccFlows'),orderBy('sort','asc')),s=>{flows=s.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(query(collection(db,'wccFlowChecks'),orderBy('sort','asc')),s=>{checks=s.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(collection(db,'wccPeople'),s=>{people=s.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(doc(db,'wccSettings','main'),s=>{if(s.exists())settings={...settings,...s.data()};render()})}
start().catch(err=>{$('#syncState').className='sync bad';$('#syncState').textContent='連線失敗';alert(err.message)});
